# Generated by Django 2.1.2 on 2018-10-21 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='tele_id',
        ),
    ]
