# Generated by Django 2.1.2 on 2018-11-02 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('forfilter', models.CharField(default='', max_length=255)),
                ('KeepForwardedCaption', models.BooleanField(default=True)),
                ('filters', models.ManyToManyField(to='admin_panel.Filter')),
            ],
            options={
                'db_table': 'Admin Channel',
            },
        ),
    ]
