# Generated by Django 2.1.2 on 2018-10-19 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='filter',
            table='Filter',
        ),
    ]
