# Generated by Django 2.1.2 on 2018-10-19 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_channel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channel',
            old_name='entity_id',
            new_name='key',
        ),
    ]
