# Generated by Django 2.1.2 on 2018-10-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='name',
        ),
        migrations.AlterField(
            model_name='session',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
