# Generated by Django 2.1.2 on 2018-11-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_auto_20181102_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminchannel',
            name='forfilter',
        ),
    ]
