# Generated by Django 2.1.2 on 2018-10-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20181024_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
