# Generated by Django 2.1.2 on 2018-10-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20181019_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='filters',
            field=models.ManyToManyField(to='admin_panel.Filter'),
        ),
        migrations.AddField(
            model_name='filter',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
