# Generated by Django 2.1.2 on 2018-10-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_telebot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='active',
        ),
        migrations.AddField(
            model_name='session',
            name='self_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
