# Generated by Django 2.1.2 on 2018-10-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_auto_20181024_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='forfilter',
            field=models.CharField(default='', max_length=255),
        ),
    ]
