# Generated by Django 2.1.2 on 2018-10-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0009_channel_forfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='KeepForwardedCaption',
            field=models.BooleanField(default=True),
        ),
    ]
